apiVersion: v1
kind: Service
metadata:
  name: {{ include "messageservice.fullname" . }}-messageservice
  labels:
    {{- include "messageservice.labels" . | nindent 4 }}
    app: messageservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5002
      protocol: TCP
      name: http
  selector:
    {{- include "messageservice.selectorLabels" . | nindent 4 }}
    app: messageservice