apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-demo-pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-secrets
        key: connectionString
auth:
  secretStore: kubernetes
