apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-demo-secrets-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    # Only for demo purposes. Not recommended for production!
    - name: secretsFile
      value: "../../dapr/self-hosted/local/dapr-demo-secrets-store.json"
