apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-demo-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        name: redisHost
    - name: redisPassword
      secretKeyRef:
        name: redisPassword
auth:
  secretStore: dapr-demo-secrets-store
