apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-demo-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
